# -*- coding: utf-8 -*-
"""Creating a Soccer/Football Pitch in Python and Pass Map

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bGo5XVPnuw6C0XzvKehzJi1eDR7B2USu

#Important Libraries
"""

import matplotlib.pyplot as plt
!pip install mplsoccer
from mplsoccer.pitch import Pitch
import pandas as pd
from pandas import json_normalize
import numpy as np
import requests
import seaborn as sns

#Read in data
df=pd.read_csv("/messibetis.csv")

df

df.head()

#Optimizng x and y
df['x']=df['x']*1.2
df['y']=df['y']*0.8
df['endX']=df['endX']*1.2
df['endY']=df['endY']*0.8

"""# Soccer Pass Map"""

fig,ax=plt.subplots(figsize=(13.5,8))
fig.set_facecolor('#22312b')
ax.patch.set_facecolor("#2E8B57")

# plot a StatsBomb pitch
pitch = Pitch(pitch_color='grass', line_color='white', stripe=True)
pitch.draw(ax=ax)
plt.gca().invert_yaxis()

for index, row in df.iterrows():
    start_x, start_y = row['x'], row['y']
    end_x, end_y = row['endX'], row['endY']

    if row['outcome'] == 'Successful':
        plt.plot([start_x, end_x], [start_y, end_y], color='blue')
        plt.scatter([start_x], [start_y], color='blue')
    elif row['outcome'] == 'Unsuccessful':
        plt.plot([start_x, end_x], [start_y, end_y], color='red')
        plt.scatter([start_x], [start_y], color='red')