# -*- coding: utf-8 -*-
"""Messi Heat Map againstReal Betis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12rByJ5DXHsC3-6RDq8fVUrxoQ0q1jqz-

#Important Libraries
"""

!pip install mplsoccer
import matplotlib.pyplot as plt
from mplsoccer.pitch import Pitch
import pandas as pd
from pandas import json_normalize
import numpy as np
import requests
import seaborn as sns

#Read in data
df=pd.read_csv("/content/messibetis.csv")

#Optimizng x and y
df['x']=df['x']*1.2
df['y']=df['y']*0.8
df['endX']=df['endX']*1.2
df['endY']=df['endY']*0.8

"""**Creating Pitch and Heat Map**"""

##Pitch
fig,ax=plt.subplots(figsize=(13.5,8))
fig.set_facecolor('#22312b')
ax.patch.set_facecolor("#2E8B57")

# plot a StatsBomb pitch
pitch = Pitch(pitch_color='grass', line_color='white', stripe=True)
pitch.draw(ax=ax)
plt.gca().invert_yaxis()

#Heat Map

kde=sns.kdeplot(
    x=df["x"],  # X coordinates
    y=df["y"],  # Y coordinates
    shade=True,
    shade_lowest=False,
    cmap='plasma',  # Renk haritası #viridis and
    alpha=.7,
    ax=ax
)

plt.xlim(0,120)
plt.ylim(0,80)
plt.title("Messi Pass Heat Map vs Real Betis",color="white",size=15)
plt.show()