# -*- coding: utf-8 -*-
"""Python Conditional Statements & Error Handling | Learn Football With Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYIt8-JU_vVDfXDU3ztNUmB4_8XnggM5
"""

team_fenerbahce_goals=3
team_barcelona_goals=2

team_fenerbahce_goals==team_barcelona_goals

#False

team_fenerbahce_goals=1
team_chelsea_goals=1

team_fenerbahce_goals==team_chelsea_goals

#True

team_fenerbahce_goals=1
team_sevilla_goals=0

team_fenerbahce_goals>=team_sevilla_goals
#True

team_barcelona_goals is team_chelsea_goals
#False

"Penalty"=="penalty"
#False

team_realmadrid_goals=4
team_besiktas_goals=2

if team_realmadrid_goals > team_besiktas_goals:
  print("Real Madrid Won!")
elif team_realmadrid_goals==team_besiktas_goals:
  print("Tie!")
else:
  print("Besiktas Won!")

team_barcelona_points=0
team_chelsea_points=0

if team_barcelona_goals > team_chelsea_goals:
  team_barcelona_points += 3
elif team_barcelona_goals < team_chelsea_goals:
  team_chelsea_points= team_chelsea_points+3
else:
  team_barcelona_points += 1
  team_chelsea_points +=  1

print(team_barcelona_points,team_chelsea_points)

if(team_realmadrid_goals>team_sevilla_goals) and (team_realmadrid_goals - team_sevilla_goals> 2):
  print("Upper Win!")
else:
  print("Looks like a normal Win.")

if(team_realmadrid_goals>team_chelsea_goals) or (team_fenerbahce_goals>team_sevilla_goals):
  print("At Least one favourite won the game!")

goals=input("Enter the number of goals:")
mins=input("Enter the number of minutes")



try:
  goals=int(goals)
  mins=int(mins)
  goals_per_match=goals/(mins/90)

  print("Goals per Match: ", goals_per_match)
except:
  print("Please try again.")

