# -*- coding: utf-8 -*-
"""Python Variables and Data Types | Learn Football With Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJ2AWNKMwXEo755_daH2aSUytnLFDzii
"""

goals=6
minutes=440.00
times_90=minutes/90.0
name="Arda"

print("Arda Guler Goals:",goals)
#print(goals) comment line
goals_per_90=goals/times_90
print('goals per 90 minute of Arda Güler:',goals_per_90)
print(goals_per_90)
type(name)

goals=input("Enter the Number of Goals: ")
minutes=input("Enter the Number of Minutes: ")
name=input("Enter the name of player: ")

print(type(goals))
print(type(minutes))
print(type(name))

goals=int(goals)
minutes=int(minutes)

print(type(goals))
print(type(minutes))
print(type(name))

time_per_90=minutes/90
goals_per_90=goals/time_per_90

print("Goals per 90 minute of",name,":",goals_per_90)